<?php
/*
 * Request price button
 * */
?>
<button type="submit"
        title=""
        style="margin-left: 50px"
        class="action primary tocart"
        id="request-price-button"
        data-mage-init='{"buttonPopup": {}}'>
    <span><?= $block->getButtonLabel(); ?></span>
</button>
<div id="popup-modal-form" style="display:none;">
    <?php echo $block->getChildHtml('product.request.price.form'); ?>
</div>
